apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.appLabel }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.selector }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: API_URL
              value: {{ .Values.frontend.env.apiUrl }}
            - name: POSTGRESQL_SERVICE_HOST
              value: {{ .Values.frontend.env.postgresqlHost }}
            - name: POSTGRESQL_SERVICE_PORT
              value: {{ .Values.frontend.env.postgresqlPort }}
            - name: POSTGRESQL_DB
              value: {{ .Values.frontend.env.postgresqlDb }}
            - name: POSTGRESQL_USER
              value: {{ .Values.frontend.env.postgresqlUser }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.frontend.env.secretName }}
                  key: password
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.frontend.selector }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
